# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - jokessrv1

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: sbt compile package
      

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'jokessrv1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88fc2295243e4ec48ab8d27aca49ede0 }}
        package: '${{ github.workspace }}/target/scala*/*.jar'